module.exports = {
  // safelist: process.env.NODE_ENV === "development" ? [{ pattern: /.*/ }] : [],
  // mode: 'jit',
  content: [
    './components/**/*.{js,vue,ts}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
    './plugins/**/*.{js,ts}',
    './nuxt.config.{js,ts}',
  ],
  theme: {
    extend: {
      colors: {
        'blue-dark': '#1A2D5B',
        'gray-dark': '#667085',
        'gray-darker': '#101828',
        'gray-light': 'rgba(229, 229, 229, 0.22)',
        'gray-lighter': '#E4E7EC',

        'theme-navbar-bg': 'var(--theme-navbar-bg)',
        'theme-navbar-text': 'var(--theme-navbar-text)',
        'theme-primary': 'var(--theme-primary)',
        'theme-banner': 'var(--theme-banner)',
        'theme-banner-text': 'var(--theme-banner-text)',
        'theme-banner-border': 'var(--theme-banner-border)',
        'theme-mobile-sidebar': 'var(--theme-mobile-sidebar)',
        'theme-primary-negative': 'var(--theme-primary-negative)',
        'theme-primary-negative-z': 'var(--theme-primary-negative-z)',
        'theme-primary-negative-y': 'var(--theme-primary-negative-y)',
        'theme-green': 'var(--theme-green)',
        'theme-primary-dark': 'var(--theme-primary-dark)',
        'theme-secondary': 'var(--theme-secondary)',
        'theme-secondary-lighter': 'var(--theme-secondary-lighter)',
        'theme-yellow': 'var(--theme-yellow)',
        'theme-blue': 'var(--theme-blue)',
        'theme-blue-2': 'var(--theme-blue-2)',
        'theme-blue-3': 'var(--theme-blue-3)',
        'theme-blue-light': 'var(--theme-blue-light)',
        'theme-primary-lighter': 'var(--theme-primary-lighter)',
        'theme-primary-lighter-2': 'var(--theme-primary-lighter-2)',
        'theme-primary-lighter-3': 'var(--theme-primary-lighter-3)',
        'theme-black': 'var(--theme-black)',
        'theme-gray-lighter': 'var(--theme-gray-lighter)',
        'theme-gray': 'var(--theme-gray)',
        'theme-gray-2': 'var(--theme-gray-2)',
        'theme-gray-3': 'var(--theme-gray-3)',
        'theme-gray-light': 'var(--theme-gray-light)',
        'theme-white-transparent': 'var(--theme-white-transparent)',
        'theme-primary-text': 'var(--theme-primary-text)',
        'theme-primary-text-lighter': 'var(--theme-primary-text-lighter)',
        'theme-text-oa': 'var(--theme-text-oa)',
        'theme-footer-text': 'var(--theme-footer-text)',
        'theme-footer': 'var(--theme-footer)',
      },
    },
  },
  plugins: [],
}
